Refactor Guest Video Setup

diff --git a/files/usr/local/bin/guest-viewer.j2 b/files/usr/local/bin/guest-viewer.j2
--- a/files/usr/local/bin/guest-viewer.j2
+++ b/files/usr/local/bin/guest-viewer.j2
@@ -1,22 +1,25 @@
 {%- extends 'files/guest.instances.inc.j2' -%}{%- block body -%}
 #!/bin/bash
 
-VIEWER_MODE=spice
-
-{% if looking_glass %}
 if [[ -f "{{ config_file }}" ]] ; then
   source "{{ config_file }}"
-
-  if [[ "$VIDEO" == "looking-glass" ]]; then
-    VIEWER_MODE="looking-glass"
-  fi
 fi
 
-{% endif %}
-if [[ "$VIEWER_MODE" == "spice" ]] ; then
+{% if looking_glass == true %}
+if [[ "x$BOOTSTRAP" != "x" ]]; then
   exec spicy --uri "spice+unix://{{ spice_socket }}"
-elif [[ "$VIEWER_MODE" == "looking-glass" ]] ; then
-  exec looking-glass-client -f "{{ looking_glass_file }}" -c "{{ spice_socket }}" -p 0 -o opengl:amdPinnedMem=0 -k -a
+else
+  exec looking-glass-client -f "{{ looking_glass_file }}" -c "{{ spice_socket }}" -p 0 -o "opengl:amdPinnedMem=0" -a &
 fi
+{% elif video_hardware == 'none' %}
+if [[ "x$BOOTSTRAP" != "x" ]]; then
+  exec spicy --uri "spice+unix://{{ spice_socket }}"
+else
+  echo "ERROR: No video output available from the guest"
+  exit 1
+fi
+{% else %}
+exec spicy --uri "spice+unix://{{ spice_socket }}"
+{% endif %}
 
 {% endblock %}
